/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
#include <iostream>
using namespace std;

typedef unsigned long uint64;

uint64 getFibSum(int limit = 4000000) {
  uint64 cumSum = 0;
  int sum = 1;
  int prev = 0;

  while (1) {
    int temp = sum;
    sum += prev;
    prev = temp; 
    
    if (sum > limit) {
      break;
    }
    if ((sum % 2) == 0) {
      cumSum += sum; 
    }
  }
  
  return cumSum;
}

int main(int argc, char** argv) {
  cout << getFibSum() << endl;
  return 0;
}
